
export const metadata = {
  title: "Job |  O-Projects",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
