import "@/styles/globals.scss";

import Provder from "@/components/layout/Provder";

export const metadata = {
  title: "Home |  O-Projects",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-b900"
      >
        <Provder>
          {children}
        </Provder>
      </body>
    </html>
  );
}
